package com.dumbpug.dungeony.session.level.tile;

/**
 * Enumeration of every unique tile type.
 */
public enum TileType {
	/**
	 * Empty Types
	 */
	EMPTY,
	
	/**
	 * Wall Types
	 */
	STONE_WALL,
	STONE_WALL_BROKEN,
	
	/**
	 * Door Types
	 */
	DOOR_NOLOCK_CLOSED,
	DOOR_NOLOCK_OPEN,
	
	DOOR_ONELOCK,
	DOOR_ONELOCK_ONEKEY_CLOSED,
	DOOR_ONELOCK_ONEKEY_OPEN,
	
	DOOR_TWOLOCK,
	DOOR_TWOLOCK_ONEKEY,
	DOOR_TWOLOCK_TWOKEY_CLOSED,
	DOOR_TWOLOCK_TWOKEY_OPEN,
	
	DOOR_THREELOCK,
	DOOR_THREELOCK_ONEKEY,
	DOOR_THREELOCK_TWOKEY,
	DOOR_THREELOCK_THREEKEY_OPEN,
	DOOR_THREELOCK_THREEKEY_CLOSED,
	
	DOOR_FOURLOCK,
	DOOR_FOURLOCK_ONEKEY,
	DOOR_FOURLOCK_TWOKEY,
	DOOR_FOURLOCK_THREEKEY,
	DOOR_FOURLOCK_FOURKEY_OPEN,
	DOOR_FOURLOCK_FOURKEY_CLOSED,
	
	DOOR_FIVELOCK,
	DOOR_FIVELOCK_ONEKEY,
	DOOR_FIVELOCK_TWOKEY,
	DOOR_FIVELOCK_THREEKEY,
	DOOR_FIVELOCK_FOURKEY,
	DOOR_FIVELOCK_FIVEKEY_OPEN,
	DOOR_FIVELOCK_FIVEKEY_CLOSED,
	
	DOOR_BOSS,
	DOOR_BOSS_CLOSED,
	DOOR_BOSS_OPEN,
	
	DOOR_SHOP,
	DOOR_SHOP_CLOSED,
	DOOR_SHOP_OPEN
}